src/main/java/edu/mx/unsis/unsiSmile/controller/GenderController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/GenderRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/GenderResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/GenderMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/GenderModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/GroupModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IGenderRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/GenderService.java
=> Us 25 end point gender

src/main/java/edu/mx/unsis/unsiSmile/model/GroupModel.java
Actualización de campos para el model grupos
=> Actualización de campo en grupo

src/main/java/edu/mx/unsis/unsiSmile/controller/GroupController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/GroupRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/GroupResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/GroupMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/GroupModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/ICareerRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/CareerService.java, src/main/java/edu/mx/unsis/unsiSmile/service/GroupService.java
End point completed and tested
=> end point groups

src/main/java/edu/mx/unsis/unsiSmile/controller/RoleController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/UserController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/students/StudentController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/RoleRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/UserRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/RoleResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/UserResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/students/StudentResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/RoleMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/UserMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/StudentMapper.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IRoleRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IUserRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/RoleService.java, src/main/java/edu/mx/unsis/unsiSmile/service/UserService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
=> Us 23 end point student

src/main/java/edu/mx/unsis/unsiSmile/controller/students/StudentSemesterController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentSemesterRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/students/StudentSemesterResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/SemesterMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/StudentSemesterMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/students/StudentSemesterModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentSemesterRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/UserService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentSemesterService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
falta probar la acción actualizar
=> end point student_semester

src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/MedicalHistoryController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/MedicalHistoryRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/VitalSignsRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/MedicalHistoryResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/MedicalHistoryMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/addresses/AddressModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/MedicalHistoryModel.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/VitalSignsService.java
actualizar el request para pedir el id del paciente
validar que el paciente tenga una historia clinica
utilizar el id del paciente para mapear los signos vitales a la historia clinica
=> Relacionar vital_signs con medical_history

src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentPatientService.java
falata validar que para un role de estudiante solo se puedan obtener **getById** aquellos con los que está relacionado (student-patients)
=> Filtrar usuarios

src/main/java/edu/mx/unsis/unsiSmile/controller/patients/PatientController.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java
Se actualizó el método de patientService que devuelve los pacientes, 
considerar este formato al ejecutar la solicitud,  de lo contrario solo devolverá los primeros 10
> h ttp://localhost:8080/unsismile/api/v1/patients?page=1&size=2
=> Us 65 paginar pacientes

src/main/java/edu/mx/unsis/unsiSmile/controller/administrators/AdministratorController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/administrators/AdministratorRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/administrators/AdministratorResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/administrators/AdministratorMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/administrators/AdministratorsModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/administrators/IAdministratorRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/administrators/AdministratorService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
end point para administradores, falta el update
=> CRD para administradores

src/main/java/edu/mx/unsis/unsiSmile/dtos/request/AnswerRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/CatalogOptionRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/FileRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/QuestionRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/AnswerResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/AnswerTypeResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/CatalogOptionResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/CatalogResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/ClinicalHistoryCatalogResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/FileResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/FormSectionResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/QuestionResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/ValidationResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/ValidationTypeResponse.java, src/main/java/edu/mx/unsis/unsiSmile/model/AnswerModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/FileModel.java, src/main/resources/db/migration/V0.0.3__changelog.sql
Responses de las nuevas tablas para obtener la configuración de una historia clínica
=> Us 141 responses

src/main/java/edu/mx/unsis/unsiSmile/controller/files/FileController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/patients/PatientResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/students/PatientStudentResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/StudentPatientMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/StudentRes.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IQuestionRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentPatientService.java
para consulta desde administradores
Con estudiante asignado
sin estudiante, o estudiante inactivo
=> refactor: Se obtiene paciente-estudiante

src/main/java/edu/mx/unsis/unsiSmile/controller/patients/PatientController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/patients/PatientRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentReq.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java
=> feat: asignación de alumno a un paciente insertado por un admin

src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/LocalityController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/MunicipalityController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/patients/EthnicGroupController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/patients/ReligionController.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/ILocalityRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IMunicipalityRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/patients/IEthnicGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/patients/IReligionRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/LocalityService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/MunicipalityService.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/EthnicGroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/ReligionService.java
=> jpql for address

.gitignore, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/StateController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/patients/PatientController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/students/StudentController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/patients/PatientRequest.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IStateRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/patients/IPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentPatientService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
=> feat: Se implementa un search jpql para filtrar student(s).

src/main/java/edu/mx/unsis/unsiSmile/config/SpringSecurityAuditorAware.java, src/main/java/edu/mx/unsis/unsiSmile/controller/AnswerController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/AnswerRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/AnswerUpdateRequest.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/AnswerMapper.java, src/main/java/edu/mx/unsis/unsiSmile/service/AnswerService.java
Servicio de actualización de formularios
=> Actualización de formularios

src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ClinicalHistoryCatalogController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/patients/PatientController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/OdontogramRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/patients/PatientRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentPatientRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/PatientClinicalHistoryResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/patients/PatientResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/students/PatientStudentResponse.java, src/main/java/edu/mx/unsis/unsiSmile/model/patients/PatientModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IClinicalHistoryCatalogRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IPatientClinicalHistoryRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/patients/IPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistoryCatalogService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/PatientClinicalHistoryService.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentPatientService.java, src/main/resources/db/migration/V0.0.2__changelog.sql, src/main/resources/db/migration/V0.0.3__changelog.sql, src/main/resources/db/migration/V0.0.6__changelog.sql
Relación con pacientes
Obtener un paciente
=> Us 192 change patient id

src/main/java/edu/mx/unsis/unsiSmile/controller/FormSectionController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/QuestionController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ClinicalHistoryCatalogController.java, src/main/java/edu/mx/unsis/unsiSmile/model/AnswerModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IAnswerRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IPatientClinicalHistoryRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/AnswerService.java, src/main/java/edu/mx/unsis/unsiSmile/service/QuestionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistoryCatalogService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/FormSectionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/PatientClinicalHistoryService.java, src/main/resources/db/migration/V0.0.3__changelog.sql
Ahora se envía el id del paciente para hacer la construcción de la config
=> Refactor en el flujo de construir una HC

src/main/java/edu/mx/unsis/unsiSmile/controller/files/FileController.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/AnswerMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/AnswerModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IAnswerRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/files/FileService.java, src/main/resources/application.properties, src/main/resources/db/migration/V0.0.3__changelog.sql
Se cambió a tipo string para hacer match con el paciente, sustituyendo el fk_ de la historia clinica
=> fix: Cambio llave foránea de fk_patient_clinical_history a fk_patient

src/main/java/edu/mx/unsis/unsiSmile/mappers/addresses/AddressMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/addresses/LocalityMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/addresses/MunicipalityMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/addresses/NeighborhoodMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/addresses/StreetMapper.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IAddressRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/ILocalityRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IMunicipalityRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/INeighborhoodRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IStreetRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/AddressService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/HousingService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/LocalityService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/MunicipalityService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/NeighborhoodService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/StateService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/StreetService.java
- Modificados mappers y repositorios para gestionar la inserción del domicilio.
- Actualizados los servicios de AddressService, HousingService, LocalityService, MunicipalityService, NeighborhoodService, StateService y StreetService para que los datos se creen si no existen.
- Datos de prueba
=> feat: Se inserta domicilio con datos relacionados si no existen

src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/HousingController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/LocalityController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/MunicipalityController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/NeighborhoodController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/StateController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/addresses/StreetController.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/ILocalityRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IMunicipalityRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/INeighborhoodRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/addresses/IStreetRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/LocalityService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/MunicipalityService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/NeighborhoodService.java, src/main/java/edu/mx/unsis/unsiSmile/service/addresses/StreetService.java
Parámetros a envar, también se agregó paginación de los resultados
Resultado, (Se repite el patrón para el resto)
=> Filtrar direcciones

src/main/java/edu/mx/unsis/unsiSmile/service/administrators/AdministratorService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/PersonService.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
- Se valida si existe o no el registro enviado antes de crear un estudiante, paciente o administrador
=> feat: validar el registro persona

src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/controller/AuthController.java, src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/dtos/PasswordUpdateRequest.java, src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/service/AuthService.java
=> feat: Servicio para actualizar la contraseña

src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/SemesterRequest.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/SemesterMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/students/SemesterModel.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/SemesterService.java
cambio nombre starDate >  startDate
=> fix: cambio nombre starDate >  startDate

src/main/resources/db/migration/V0.0.10__changelog.sql, src/main/resources/db/migration/V0.0.7__changelog.sql
=> Fix question order

src/main/resources/db/migration/V0.0.14__changelog.sql, src/main/resources/db/migration/V0.0.14_changelog.sql, src/main/resources/db/migration/V0.0.6__changelog.sql, src/main/resources/db/migration/V0.0.7__changelog.sql
- Se Homologan preguntas en : antecedentes personales patológicos, Interrogatorio y exploración de cavidad
- Se agrego changelog para hc Historia clinica Odontología preventiva y salud pública
=> Us 222 harmonize medical records

src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/model/UserModel.java
=> fix: first login

src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IClinicalHistorySectionRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistorySectionService.java
to use composite key and adjust service methods accordingly
=> refactor: update ClinicalHistorySectionRepository 

src/main/java/edu/mx/unsis/unsiSmile/controller/DashboardController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/professors/ProfessorGroupController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/professors/ProfessorGroupRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/GroupRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/DashboardResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/professors/ProfessorGroupResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/students/GroupResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/professors/ProfessorGroupMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/GroupMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/professors/ProfessorGroupModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/patients/IPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/professors/IProfessorGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/professors/IProfessorRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentPatientRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/DashboardService.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ProfessorGroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/GroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java, src/main/resources/db/migration/V0.0.13__changelog.sql
ruta
Se tendrá que iterar sobre esta estructura para mostrar los datos
=> Us 182 estadisticas

src/main/resources/db/migration/V0.0.10__changelog.sql, src/main/resources/db/migration/V0.0.14__changelog.sql, src/main/resources/db/migration/V0.0.6__changelog.sql, src/main/resources/db/migration/V0.0.7__changelog.sql
Se actualiza el poblado de las opciones para los catálogos
=> fix(catalogs): Poblado de opciones

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/students/StudentController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/students/GroupResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/GroupMapper.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/GroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentGroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
se agrega el grupo, carrera y semestre en el response de estudiantes
=> Student information

src/main/java/edu/mx/unsis/unsiSmile/repository/IRoleRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/UserService.java
Validación de rol antes de insertar para no generar duplicadoos
=> fix: roles duplicados

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/common/ValidateCurp.java, src/main/java/edu/mx/unsis/unsiSmile/common/ValidationUtils.java, src/main/java/edu/mx/unsis/unsiSmile/controller/professors/ProfessorController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/students/StudentController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/professors/ProfessorRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/CareerRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/GroupRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/SemesterRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentReq.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/students/StudentRequest.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/GroupMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/students/StudentMapper.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/PersonService.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/ProgressNoteService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/CareerService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/GroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentGroupService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentService.java
Se refactoriza el request y service de carrera  para manejar los mensajes desde otro archivo
=> Us 147 validaciones

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/common/ValidateCurp.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/GenderRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/PersonRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/patients/PatientRequest.java
- Agregar validación para el campo de género de ID
- Actualizar las anotaciones de validación en las clases de solicitud
- Eliminar la validación de género en el ValidateCurp
=> fix: Validación del campo género

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/FormSectionController.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/FormSectionService.java
- Mejorar el manejo de secciones del formulario con mensajes de error mejorados
- Validación de ID
=> fix: Corregir el response de una sección

src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/controller/AuthController.java, src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/service/AuthService.java, src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/service/UserService.java
- Se implementó la funcionalidad para restablecer la contraseña de un usuario a un valor predeterminado.
=> feat: Setear la contraseña a default para el usuario

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/professors/ClinicalAreaController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/professors/ClinicalAreaResponse.java, src/main/java/edu/mx/unsis/unsiSmile/repository/professors/IProfessorClinicalAreaRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ClinicalAreaService.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ProfessorClinicalAreaService.java
por área clínica y actualizar el manejo de respuestas relacionadas
=> feat: Implementar la paginación para buscar profesores

src/main/java/edu/mx/unsis/unsiSmile/authenticationProviders/controller/AuthController.java, src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/UserController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/StatusClinicalHistoryController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/StatusClinicalHistoryRequest.java
Se agrega información de operaciones para una mejor documentación de la API
=> feat: Se actualiza las rutas de los endPoints

src/main/java/edu/mx/unsis/unsiSmile/dtos/response/professors/ProfessorResponse.java, src/main/java/edu/mx/unsis/unsiSmile/repository/professors/IClinicalAreaRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ClinicalAreaService.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ProfessorClinicalAreaService.java
=> refactor: Update ClinicalAreaRepository and ClinicalAreaService

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/repository/professors/IProfessorClinicalAreaRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ClinicalAreaService.java, src/main/java/edu/mx/unsis/unsiSmile/service/professors/ProfessorClinicalAreaService.java
para profesores de áreas clínicas, por área clínica y actualizar mensajes de respuesta
=> feat: Agregar gestión de eliminación

src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/treatments/TreatmentDetailModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/treatments/TreatmentDetailToothModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/treatments/TreatmentModel.java
Para eliminar los warnings que causaba el @Data por el extends
=> feat: replace @Data with @Getter and @Setter in treatment models

src/main/java/edu/mx/unsis/unsiSmile/common/Constants.java, src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ClinicalHistoryCatalogController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/patients/PatientController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/treatments/TreatmentDetailRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/patients/PatientResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/treatments/TreatmentDetailMapper.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IClinicalHistoryCatalogRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IPatientClinicalHistoryRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/treatments/ITreatmentDetailRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistoryCatalogService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistorySectionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/FormSectionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/PatientClinicalHistoryService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ReviewStatusService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailService.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/PatientService.java
Se actualizá el flujo para las HC generales y la forma de consultar una en particular
=> Us 332 fix tratamientos hc

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/files/FileController.java, src/main/java/edu/mx/unsis/unsiSmile/model/files/GeneralFileModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/patients/ProgressNoteFileModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/files/IGeneralFileRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/files/FileService.java, src/main/java/edu/mx/unsis/unsiSmile/service/files/GeneralFileService.java, src/main/resources/db/migration/V0.0.18__changelog.sql, src/main/resources/db/migration/V0.0.22__changelog.sql
Se agregaron los servicios para los archivos generales (carga, descarga, visualización y eliminar)
=> Us 330 refactor modelo y manejo de archivos

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ReviewStatusController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/treatments/TreatmentController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/treatments/TreatmentDetailController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/ClinicalHistoryCatalogResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/treatments/TreatmentDetailResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/treatments/TreatmentDetailMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/ReviewStatus.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IReviewStatusRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/treatments/ITreatmentDetailRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/treatments/ITreatmentDetailToothRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/students/IStudentGroupRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistoryCatalogService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ReviewStatusService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailToothService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentService.java, src/main/java/edu/mx/unsis/unsiSmile/service/students/StudentGroupService.java
. Actualizaciones para enviar a revisión el tratamiento
. Actualizaciones para marcar un tratamiento como finalizado
. Servicio para actualizar fecha de un tratamiento y órganos dentarios involucrados (si es el caso)
=> Us 341 feat tratamientos paciente alumno

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/patients/ProgressNoteController.java, src/main/java/edu/mx/unsis/unsiSmile/service/patients/ProgressNoteService.java
Se actualiza el nombre del endpoint para generar el pdf y se expone el de descarga
=> feat: add PDF generation and download functionality for progress notes

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ClinicalHistoryCatalogController.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/EMedicalRecords.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistoryCatalogService.java
=> feat: obtener HC 

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/DentalProphylaxisController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/DentalProphylaxisRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/EnumToothId.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/ToothCodeRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/DentalProphylaxisResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/ToothCodeResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/DentalProphylaxisMapper.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/SOHIMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/DentalProphylaxisModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/SOHIModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/SOHIToothCodeModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/ISOHIRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/ISOHITootCodeRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/DentalProphylaxisService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/SOHIService.java, src/main/resources/db/migration/V0.0.19__changelog.sql
al modelo de profilaxis y se actualiza las clases relacionadas
=> feat: Se agrega el campo porcentaje 

src/main/java/edu/mx/unsis/unsiSmile/controller/FormSectionController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/QuestionController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ClinicalHistoryCatalogController.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/ReviewStatusController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/QuestionRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/request/medicalHistories/FormSectionRequest.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/FormSectionResponse.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/ReviewStatusResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/ReviewStatusMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/FormSectionModel.java, src/main/java/edu/mx/unsis/unsiSmile/model/utils/ClinicalHistorySectionModelPk.java, src/main/java/edu/mx/unsis/unsiSmile/repository/IQuestionRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IFormSectionRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/IReviewStatusRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/QuestionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ClinicalHistorySectionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/FormSectionService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/ReviewStatusService.java, src/main/java/edu/mx/unsis/unsiSmile/service/periodontogram/PeriodontogramService.java, src/main/resources/db/migration/V0.0.10__changelog.sql, src/main/resources/db/migration/V0.0.12__changelog.sql, src/main/resources/db/migration/V0.0.13__changelog.sql, src/main/resources/db/migration/V0.0.16__changelog.sql, src/main/resources/db/migration/V0.0.3__changelog.sql, src/main/resources/db/migration/V0.0.6__changelog.sql, src/main/resources/db/migration/V0.0.7__changelog.sql, src/main/resources/db/migration/V0.0.8__changelog.sql, src/main/resources/db/migration/V0.0.9__changelog.sql
Se actualizan los ids de secciones de las HC de Long a String
=> Us 357 refactor id de secciones

src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailService.java
en la actualización
- Se actualiza la forma de obtener el tipo de alcance para la comparación
=> fix: Se elimina la validación de paciente y tratamiento

src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/treatments/TreatmentDetailController.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailService.java
para filtrar los tratamientos asignados a un profesor
=> feat: Se agrega el parámetro de estatus

src/main/java/edu/mx/unsis/unsiSmile/common/ResponseMessages.java, src/main/java/edu/mx/unsis/unsiSmile/controller/medicalHistories/treatments/TreatmentDetailController.java, src/main/java/edu/mx/unsis/unsiSmile/dtos/response/medicalHistories/treatments/TreatmentDetailToothResponse.java, src/main/java/edu/mx/unsis/unsiSmile/mappers/medicalHistories/treatments/TreatmentDetailToothMapper.java, src/main/java/edu/mx/unsis/unsiSmile/model/medicalHistories/treatments/TreatmentDetailToothModel.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/treatments/IExecutionReviewRepository.java, src/main/java/edu/mx/unsis/unsiSmile/repository/medicalHistories/treatments/ITreatmentDetailToothRepository.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/ExecutionReviewService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailService.java, src/main/java/edu/mx/unsis/unsiSmile/service/medicalHistories/treatments/TreatmentDetailToothService.java, src/main/resources/db/migration/V0.0.15__changelog.sql
- Se agrega los comentarios y profesores asigandos al tratamiento
- Envío de dientes a revisión por separado
=> Us 374 fechas independientes por organo dentario
